<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Closedloop" Id="{0a291c2b-edcc-4387-9508-1fc34f82f1c8}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Closedloop
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>